### ISSUE TITLE
Why does TVector2.AngleBetween() have two implementations?

### ISSUE THREAD

**Issue by hcphoenix** [lnolson/Tin#1]
**The instance method:**
```
// Angle between two vectors
    func angleBetween(v: TVector2) -> Double {
        let alen = magnitude
        let blen = v.magnitude
        let a_dot_b = dot(v: v)
        return acos(a_dot_b / (alen * blen))
    }
```
IMO angleTo() would be a clearer name than angleBetween(), since it'd be written as v1.angleTo(v2).

**The static method:**
```
/**
     Calculate the angle, in radians, between two vectors.
     
     - Parameter v1: The first vector.
     - Parameter v2: The second vector.
     
     - Returns: (Double) Result (in radians) angle between v1 and v2.
    */
    public static func angleBetween(v1: TVector2, v2: TVector2) -> Double {
        var n1 = v1
        var n2 = v2
        n1.normalize()
        n2.normalize()
        let dp = dot(v1: n1, v2: n2)
        let result = acos(dp)
        //print("dp: \(dp) --- result: \(result)")
        return result
    }
```
Shouldn't v1.angleBetween(v2) be an equivalent function body here?

**Comment by lnolson** [comment]
I'm going to have to search my sample code for the reason, but I think the instance method was added to stay similar to Processing. Looks like I added this while preparing samples that are ports of Nature of Code - which I use in my Animating Virtual Worlds course. But you are correct that its redundant to have both of these, and I would remove the instance method.
