### ISSUE TITLE
Missing documented functions?

### ISSUE THREAD

**Issue by hcphoenix** [lnolson/Tin#2]
Setting a color with (gray: Double) is a thing in the documentation and shows up in all the projects students come in with, e.g. `background(gray: 0.5)`, but I can't find it in TColor, CoreGraphicsRenderer, or anywhere else. Is the repository up-to-date?

**Comment by lnolson** [comment]
background is a global function. You can find all of these drawing functions in Tin.swift. You could say that background(gray:) is a convenience function - it uses background(red:,green:,blue:) in the renderer.
